import { Experience } from "@/types";

export const experiences: Experience[] = [
  {
    period: "2025 - Atual",
    title: "Desenvolvedor Fullstack Pleno",
    company: "Conexoes",
    achievements: [
      "Arquitetou e planejou o sistema completo, desde definição de arquitetura, documentação técnica e fluxos até deploy",
      "Desenvolveu serviço de gerenciamento de notas fiscais com rastreabilidade e integração financeira",
      "Criou dashboard financeiro com métricas estratégicas para tomada de decisão",
      "Implementou gerenciamento de projetos financeiros com controle de execuções mensais",
      "Desenvolveu sistema de upload e gerenciamento de arquivos (PDF e Excel) com armazenamento seguro",
      "Criou serviço de geração automatizada de relatórios financeiros",
      "Implementou sistema de pagamentos com integração de regras de negócio financeiras",
      "Desenvolveu gerenciamento de empresas centralizando dados organizacionais",
      "Implementou autenticação JWT e sistema de permissões por perfil",
    ],
    skills: [
      "Node.js",
      "TypeScript",
      "Express",
      "Drizzle ORM",
      "PostgreSQL",
      "JWT",
      "HTTP",
      "Next.js",
      "Arquitetura de Sistemas",
      "Planejamento Técnico",
      "Backend & Frontend",
    ],
    current: true,
  },
  {
    period: "2023 - 2025",
    title: "Desenvolvedor Backend Junior",
    company: "VX Case",
    achievements: [
      "Desenvolveu sistema de gestão de campanhas promocionais com geração assíncrona via filas e jobs",
      "Implementou notificações automáticas multi-canal (SMS, e-mail, WhatsApp)",
      "Criou plataforma de regras de campanhas com configuração recursiva e flexível",
      "Desenvolveu sistema de teste de elegibilidade de produtos para campanhas",
      "Implementou geração de conteúdos multimídia (slides e vídeos) para PCTVs com armazenamento S3",
      "Desenvolveu microsserviço de upload de imagens via QR Code com WebSocket em tempo real",
      "Implementou microsserviço de tributações fiscais",
      "Desenvolveu integração com API da OTOCRM otimizando fluxos de trabalho",
    ],
    skills: [
      "Node.js",
      "TypeScript",
      "NestJS",
      "TypeORM",
      "MySQL",
      "SOLID",
      "Arquitetura Hexagonal",
      "TDD",
      "Microsserviços",
      "AWS S3",
      "WebSocket",
      "RabbitMQ",
    ],
    current: false,
  },
  {
    period: "2023",
    title: "Estágio de Desenvolvimento de Software",
    company: "VX Case",
    achievements: [
      "Desenvolveu microsserviços financeiros e fiscais utilizando Node.js",
      "Implementou testes automatizados de ponta a ponta (E2E) com Cypress",
      "Colaborou na identificação e resolução de bugs críticos em sistemas Laravel",
      "Aplicou princípios SOLID no desenvolvimento",
      "Estruturou projetos com Arquitetura Limpa garantindo alta coesão e baixo acoplamento",
    ],
    skills: [
      "Node.js",
      "TypeScript",
      "MySQL",
      "PHP",
      "Laravel",
      "Cypress",
      "Express",
      "SOLID",
      "Arquitetura Limpa",
    ],
    current: false,
  },
];
